In [30]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
from CIPEC import *

[Qibo 0.2.14|INFO|2025-02-21 15:49:01]: Using numpy backend on /CPU:0


# 1) Single-qubit basis

In [25]:
# 1-qubit CPTP maps (including T)
B = noiseless_basis(1,include_T=True)

print(f"\nThe following {len(B)} channels form a basis of 1q CPTP maps:\n{list(B.keys())}")

print(f'\nHere are their Choi matrices:')
for v in B.values():
    print(f'{np.round(v,2)}')

Loaded pre-computed basis

The following 13 channels form a basis of 1q CPTP maps:
[('H',), ('S',), ('T',), ('H', 'H'), ('H', 'S'), ('H', 'T'), ('S', 'H'), ('T', 'H'), ('H', 'S', 'H'), ('S', 'H', 'T'), ('Px',), ('Py',), ('Pz',)]

Here are their Choi matrices:
[[ 0.5  0.5  0.5 -0.5]
 [ 0.5  0.5  0.5 -0.5]
 [ 0.5  0.5  0.5 -0.5]
 [-0.5 -0.5 -0.5  0.5]]
[[1.+0.j 0.+0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j 1.+0.j]]
[[1.  +0.j   0.  +0.j   0.  +0.j   0.71-0.71j]
 [0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j  ]
 [0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j  ]
 [0.71+0.71j 0.  +0.j   0.  +0.j   1.  +0.j  ]]
[[ 1. -0. -0.  1.]
 [-0.  0.  0. -0.]
 [-0.  0.  0. -0.]
 [ 1. -0. -0.  1.]]
[[ 0.5+0.j   0.5+0.j   0. -0.5j  0. +0.5j]
 [ 0.5+0.j   0.5+0.j   0. -0.5j  0. +0.5j]
 [ 0. +0.5j  0. +0.5j  0.5+0.j  -0.5+0.j ]
 [ 0. -0.5j  0. -0.5j -0.5+0.j   0.5+0.j ]]
[[ 0.5 +0.j    0.5 +0.j    0.35-0.35j -0.35+0.35j]
 [ 0.5 +0.j    0.5 +0.j    0.35-

In [26]:
# 1-qubit CPTP maps (excluding T)
B = noiseless_basis(1,include_T=False)

print(f"\nThe following {len(B)} channels form a basis of 1q CPTP maps:\n{list(B.keys())}")
print(f'\nHere are their Choi matrices:')
for v in B.values():
    print(f'{np.round(v,2)}')

Loaded pre-computed basis

The following 13 channels form a basis of 1q CPTP maps:
[('H',), ('S',), ('H', 'H'), ('H', 'S'), ('S', 'H'), ('S', 'S'), ('H', 'S', 'H'), ('H', 'S', 'S'), ('S', 'H', 'S'), ('S', 'H', 'S', 'S'), ('Px',), ('Py',), ('Pz',)]

Here are their Choi matrices:
[[ 0.5  0.5  0.5 -0.5]
 [ 0.5  0.5  0.5 -0.5]
 [ 0.5  0.5  0.5 -0.5]
 [-0.5 -0.5 -0.5  0.5]]
[[1.+0.j 0.+0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j 1.+0.j]]
[[ 1. -0. -0.  1.]
 [-0.  0.  0. -0.]
 [-0.  0.  0. -0.]
 [ 1. -0. -0.  1.]]
[[ 0.5+0.j   0.5+0.j   0. -0.5j  0. +0.5j]
 [ 0.5+0.j   0.5+0.j   0. -0.5j  0. +0.5j]
 [ 0. +0.5j  0. +0.5j  0.5+0.j  -0.5+0.j ]
 [ 0. -0.5j  0. -0.5j -0.5+0.j   0.5+0.j ]]
[[ 0.5+0.j   0. -0.5j  0.5+0.j   0. +0.5j]
 [ 0. +0.5j  0.5+0.j   0. +0.5j -0.5+0.j ]
 [ 0.5+0.j   0. -0.5j  0.5+0.j   0. +0.5j]
 [ 0. -0.5j -0.5+0.j   0. -0.5j  0.5+0.j ]]
[[ 1.+0.j  0.+0.j  0.+0.j -1.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j 

# 2) Two-qubit basis

In [27]:
# 2-qubit CPTP maps (including T)
B = noiseless_basis(2,include_T=True)

print(f"\nThe following {len(B)} channels form a basis of 1q CPTP maps:\n{list(B.keys())}")
# print(f'\nHere are their Choi matrices:')
# for v in B.values():
#     print(f'{np.round(v,2)}')

Loaded pre-computed basis

The following 241 channels form a basis of 1q CPTP maps:
[('HI',), ('IH',), ('SI',), ('IS',), ('HS',), ('SH',), ('CX',), ('XC',), ('TI',), ('IT',), ('HT',), ('TH',), ('ST',), ('TS',), ('HI', 'HI'), ('HI', 'IH'), ('HI', 'SI'), ('HI', 'SH'), ('HI', 'CX'), ('HI', 'XC'), ('HI', 'TI'), ('HI', 'TH'), ('HI', 'ST'), ('HI', 'TS'), ('IH', 'IS'), ('IH', 'HS'), ('IH', 'CX'), ('IH', 'XC'), ('IH', 'IT'), ('IH', 'HT'), ('IH', 'ST'), ('IH', 'TS'), ('SI', 'HI'), ('SI', 'IS'), ('SI', 'HS'), ('SI', 'CX'), ('SI', 'XC'), ('SI', 'HT'), ('SI', 'ST'), ('IS', 'IH'), ('IS', 'SH'), ('IS', 'CX'), ('IS', 'XC'), ('IS', 'TH'), ('HS', 'IH'), ('HS', 'SI'), ('HS', 'SH'), ('HS', 'CX'), ('HS', 'XC'), ('HS', 'TH'), ('HS', 'TS'), ('SH', 'HI'), ('SH', 'IS'), ('SH', 'HS'), ('SH', 'CX'), ('SH', 'XC'), ('SH', 'HT'), ('SH', 'ST'), ('CX', 'HI'), ('CX', 'IH'), ('CX', 'IS'), ('CX', 'HS'), ('CX', 'SH'), ('CX', 'XC'), ('CX', 'TI'), ('CX', 'IT'), ('CX', 'HT'), ('CX', 'TH'), ('CX', 'ST'), ('CX', 'TS'), ('XC'

In [28]:
# 2-qubit CPTP maps (excluding T)
B = noiseless_basis(2,include_T=False)

print(f"\nThe following {len(B)} channels form a basis of 1q CPTP maps:\n{list(B.keys())}")
# print(f'\nHere are their Choi matrices:')
# for v in B.values():
#     print(f'{np.round(v,2)}')

Loaded pre-computed basis

The following 241 channels form a basis of 1q CPTP maps:
[('HI',), ('IH',), ('SI',), ('IS',), ('HS',), ('SH',), ('CX',), ('XC',), ('HI', 'HI'), ('HI', 'IH'), ('HI', 'SI'), ('HI', 'SH'), ('HI', 'CX'), ('HI', 'XC'), ('IH', 'IS'), ('IH', 'HS'), ('IH', 'CX'), ('IH', 'XC'), ('SI', 'HI'), ('SI', 'SI'), ('SI', 'IS'), ('SI', 'HS'), ('SI', 'SH'), ('SI', 'CX'), ('SI', 'XC'), ('IS', 'IH'), ('IS', 'IS'), ('IS', 'HS'), ('IS', 'SH'), ('IS', 'CX'), ('IS', 'XC'), ('HS', 'IH'), ('HS', 'SI'), ('HS', 'SH'), ('HS', 'CX'), ('HS', 'XC'), ('SH', 'HI'), ('SH', 'IS'), ('SH', 'HS'), ('SH', 'CX'), ('SH', 'XC'), ('CX', 'HI'), ('CX', 'IH'), ('CX', 'IS'), ('CX', 'HS'), ('CX', 'SH'), ('CX', 'XC'), ('XC', 'HI'), ('XC', 'IH'), ('XC', 'SI'), ('XC', 'HS'), ('XC', 'SH'), ('XC', 'CX'), ('HI', 'IH', 'CX'), ('HI', 'IH', 'XC'), ('HI', 'SI', 'HI'), ('HI', 'SI', 'SI'), ('HI', 'SI', 'HS'), ('HI', 'SI', 'SH'), ('HI', 'SI', 'CX'), ('HI', 'SI', 'XC'), ('HI', 'SH', 'HI'), ('HI', 'SH', 'IS'), ('HI', 'SH', 